/* Private entry points run before ordinary CLI initialization. This module must
 * not import the command registry, browser, settings or project runtime. */

const MAX_VIEW_HEADER_BYTES = 16 * 1024;

async function readPrivateHeader(): Promise<string> {
    const byte = new Uint8Array(1);
    const parts: number[] = [];
    while (parts.length < MAX_VIEW_HEADER_BYTES) {
        const count = await Deno.stdin.read(byte);
        if (count === null) throw new Error("Remote view configuration is missing or incomplete");
        if (byte[0] === 10) return new TextDecoder("utf-8", { fatal: true }).decode(new Uint8Array(parts));
        parts.push(byte[0]);
    }
    throw new Error("Remote view configuration is too large");
}

/** Run the bounded proof outside the supervisor so stalled resource reads cannot stop supervision. */
export async function runRemoteModelProofEntry(): Promise<void> {
    if (!Deno.build.standalone || Deno.args.length !== 1 || Deno.args[0] !== "--remote-model-proof") {
        throw new Error("Remote model proof requires its own compiled process");
    }
    const input = JSON.parse(await readPrivateHeader());
    const { runRemoteModelProof } = await import("./model-proof.ts");
    const abort = new AbortController();
    // EOF means the supervising process ended, even when it could not signal us.
    void Deno.stdin.read(new Uint8Array(1)).then(() => abort.abort(), () => abort.abort());
    await runRemoteModelProof({
        proof: input.proof,
        connection: input.connection,
        cwd: input.cwd,
        // The supervisor owns this mount. It terminates the proof process on loss.
        mount: { ...input.mount, lost: new Promise<void>(() => {}), close: () => Promise.resolve() },
        signal: abort.signal,
    });
}

/** Report only the embedded identity of this executable; never start the CLI. */
export async function runRemotePreflight(): Promise<void> {
    // Generated by the build. A source run without an explicit build cannot
    // claim to be a remote artifact.
    const [{ BUILD_ID, REMOTE_PROTOCOL_VERSION }, { VERSION }] = await Promise.all([
        import("../build-identity.js"),
        import("../version.js"),
    ]);
    if (!/^[a-f0-9]{64}$/.test(BUILD_ID) || !Number.isInteger(REMOTE_PROTOCOL_VERSION)) {
        throw new Error("Invalid remote build identity");
    }
    console.log(JSON.stringify({ buildId: BUILD_ID, protocol: REMOTE_PROTOCOL_VERSION, version: VERSION }));
}

/** Read the complete view configuration before starting ProcessTerminal. */
export async function runRemoteView(): Promise<void> {
    const header = await readPrivateHeader();
    const { parseRemoteConnectionViewConfig, showRemoteConnectionView } = await import(
        "../../ui/tui/remote-connection-view.ts"
    );
    const config = parseRemoteConnectionViewConfig(header);
    const { initRunWieldTheme } = await import("../../ui/theme/theme.js");
    initRunWieldTheme(); // Embedded theme only; no settings lookup or profile initialization.
    const { initTUI, stopTUI } = await import("../../ui/tui/tui.ts");
    try {
        await showRemoteConnectionView(initTUI(), config);
    } finally {
        stopTUI();
    }
}
