/* Private entry points run before ordinary CLI initialization. This module must
 * not import the command registry, browser, settings or project runtime. */

const MAX_VIEW_HEADER_BYTES = 16 * 1024;

async function readViewHeader(): Promise<string> {
    const byte = new Uint8Array(1);
    const parts: number[] = [];
    while (parts.length < MAX_VIEW_HEADER_BYTES) {
        const count = await Deno.stdin.read(byte);
        if (count === null) throw new Error("Remote view configuration is missing or incomplete");
        if (byte[0] === 10) return new TextDecoder("utf-8", { fatal: true }).decode(new Uint8Array(parts));
        parts.push(byte[0]);
    }
    throw new Error("Remote view configuration is too large");
}

/** Report only the embedded identity of this executable; never start the CLI. */
export async function runRemotePreflight(): Promise<void> {
    // Generated by the build. A source run without an explicit build cannot
    // claim to be a remote artifact.
    const [{ BUILD_ID, REMOTE_PROTOCOL_VERSION }, { VERSION }] = await Promise.all([
        import("../build-identity.js"),
        import("../version.js"),
    ]);
    if (!/^[a-f0-9]{64}$/.test(BUILD_ID) || !Number.isInteger(REMOTE_PROTOCOL_VERSION)) {
        throw new Error("Invalid remote build identity");
    }
    console.log(JSON.stringify({ buildId: BUILD_ID, protocol: REMOTE_PROTOCOL_VERSION, version: VERSION }));
}

/** Read the complete view configuration before starting ProcessTerminal. */
export async function runRemoteView(): Promise<void> {
    const header = await readViewHeader();
    const { parseRemoteConnectionViewConfig, showRemoteConnectionView } = await import(
        "../../ui/tui/remote-connection-view.ts"
    );
    const config = parseRemoteConnectionViewConfig(header);
    const { initRunWieldTheme } = await import("../../ui/theme/theme.js");
    initRunWieldTheme(); // Embedded theme only; no settings lookup or profile initialization.
    const { initTUI, stopTUI } = await import("../../ui/tui/tui.ts");
    try {
        await showRemoteConnectionView(initTUI(), config);
    } finally {
        stopTUI();
    }
}
