/**
 * @module shared/version
 *
 * Generated by scripts/write-version.js. The build pipeline overwrites
 * this file with the current build version before `deno compile`.
 */

export const VERSION = "2c99f9f3f";
