/**
 * @module scripts/write-version.test
 */

import { assertEquals, assertThrows } from "@std/assert";
import { getExplicitBuildVersion, getGitHubTagName, resolveBuildVersion, writeVersionFile } from "./write-version.js";

/**
 * @param {Record<string, string | undefined>} values
 * @returns {(name: string) => string | undefined}
 */
function env(values) {
    return (name) => values[name];
}

/**
 * @param {Record<string, string | undefined>} values
 * @returns {(args: string[]) => string | undefined}
 */
function git(values) {
    return (args) => values[args.join(" ")];
}

Deno.test("getGitHubTagName prefers the explicit GitHub tag ref name", () => {
    const tag = getGitHubTagName(env({
        GITHUB_REF_TYPE: "tag",
        GITHUB_REF_NAME: "v1.2.3",
        GITHUB_REF: "refs/tags/ignored",
    }));

    assertEquals(tag, "v1.2.3");
});

Deno.test("getGitHubTagName falls back to parsing GITHUB_REF tag refs", () => {
    const tag = getGitHubTagName(env({
        GITHUB_REF: "refs/tags/release/v1.2.3",
    }));

    assertEquals(tag, "release/v1.2.3");
});

Deno.test("getExplicitBuildVersion accepts stable and candidate release identities", () => {
    assertEquals(getExplicitBuildVersion(env({ WLD_BUILD_VERSION: "v1.2.3" })), "v1.2.3");
    assertEquals(getExplicitBuildVersion(env({ WLD_BUILD_VERSION: "v1.2.3-rc.1" })), "v1.2.3-rc.1");
    assertEquals(getExplicitBuildVersion(env({ WLD_BUILD_VERSION: "   " })), undefined);
});

Deno.test("getExplicitBuildVersion rejects unsafe explicit identities", () => {
    assertThrows(() => getExplicitBuildVersion(env({ WLD_BUILD_VERSION: "abc123" })), Error, "WLD_BUILD_VERSION");
    assertThrows(() => getExplicitBuildVersion(env({ WLD_BUILD_VERSION: "v1.2.3-rc.0" })), Error, "positive");
    assertThrows(() => getExplicitBuildVersion(env({ WLD_BUILD_VERSION: "v1.2.3/bad" })), Error, "WLD_BUILD_VERSION");
});

Deno.test("resolveBuildVersion uses explicit build version before GitHub tag and git metadata", () => {
    const version = resolveBuildVersion({
        readEnv: env({
            WLD_BUILD_VERSION: "v2.0.0-rc.1",
            GITHUB_REF_TYPE: "tag",
            GITHUB_REF_NAME: "v2.0.0",
        }),
        runGit: git({
            "describe --tags --exact-match HEAD": "v1.9.0",
            "rev-parse --short HEAD": "abc1234",
        }),
    });

    assertEquals(version, "v2.0.0-rc.1");
});

Deno.test("resolveBuildVersion uses GitHub tag before git metadata", () => {
    const version = resolveBuildVersion({
        readEnv: env({
            GITHUB_REF_TYPE: "tag",
            GITHUB_REF_NAME: "v2.0.0",
        }),
        runGit: git({
            "describe --tags --exact-match HEAD": "v1.9.0",
            "rev-parse --short HEAD": "abc1234",
        }),
    });

    assertEquals(version, "v2.0.0");
});

Deno.test("resolveBuildVersion uses exact local tag before short hash", () => {
    const version = resolveBuildVersion({
        readEnv: env({}),
        runGit: git({
            "describe --tags --exact-match HEAD": "v1.2.3",
            "rev-parse --short HEAD": "abc1234",
        }),
    });

    assertEquals(version, "v1.2.3");
});

Deno.test("resolveBuildVersion falls back to short hash and then dev", () => {
    assertEquals(
        resolveBuildVersion({ readEnv: env({}), runGit: git({ "rev-parse --short HEAD": "abc1234" }) }),
        "abc1234",
    );
    assertEquals(resolveBuildVersion({ readEnv: env({}), runGit: git({}) }), "dev");
});

Deno.test("writeVersionFile leaves matching files untouched", async () => {
    const filePath = await Deno.makeTempFile();
    const content = `/**
 * @module shared/version
 *
 * Generated by scripts/write-version.js. The build pipeline overwrites
 * this file with the current build version before \`deno compile\`.
 */

export const VERSION = "abc1234";
`;

    try {
        await Deno.writeTextFile(filePath, content);
        await Deno.chmod(filePath, 0o444);

        await writeVersionFile(filePath, "abc1234");

        assertEquals(await Deno.readTextFile(filePath), content);
    } finally {
        await Deno.chmod(filePath, 0o644).catch(() => {});
        await Deno.remove(filePath).catch(() => {});
    }
});
