/**
 * @module scripts/write-version
 *
 * Build-time helper: writes the current release tag or git short hash into
 * `src/shared/version.js` so the compiled binary reports its build version.
 * Run before `deno compile`. Falls back to "dev" if git is unavailable
 * or the working tree is not a repo.
 */

const FILE_PATH = "src/shared/version.js";
const EXPLICIT_BUILD_VERSION_ENV = "WLD_BUILD_VERSION";
const SAFE_BUILD_VERSION_PATTERN = /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-rc\.([1-9]\d*))?$/;

/**
 * @typedef {(name: string) => string | undefined} EnvReader
 */

/**
 * @typedef {(args: string[]) => string | undefined} GitRunner
 */

/**
 * @typedef {Object} BuildVersionPort
 * @property {EnvReader} readEnv
 * @property {GitRunner} runGit
 */

/**
 * Read an environment variable, returning undefined when env access is not
 * allowed. This keeps non-release build paths on the existing git fallback.
 *
 * @param {string} name
 * @returns {string | undefined}
 */
function readEnvValue(name) {
    try {
        return Deno.env.get(name);
    } catch (_e) {
        return undefined;
    }
}

/**
 * @param {string[]} args
 * @returns {string | undefined}
 */
function runGitCommand(args) {
    try {
        const cmd = new Deno.Command("git", { args, stdout: "piped", stderr: "null" });
        const { success, stdout } = cmd.outputSync();
        if (!success) return undefined;
        return new TextDecoder().decode(stdout).trim() || undefined;
    } catch (_e) {
        return undefined;
    }
}

/**
 * @param {string} value
 * @returns {string | undefined}
 */
function normalizeExplicitBuildVersion(value) {
    const trimmed = value.trim();
    if (!trimmed) return undefined;
    if (!SAFE_BUILD_VERSION_PATTERN.test(trimmed)) {
        throw new Error(`${EXPLICIT_BUILD_VERSION_ENV} must be a WLD release tag like v1.2.3 or v1.2.3-rc.1.`);
    }
    const rcMatch = trimmed.match(/-rc\.(\d+)$/);
    if (rcMatch && Number(rcMatch[1]) < 1) {
        throw new Error(`${EXPLICIT_BUILD_VERSION_ENV} release-candidate ordinal must be positive.`);
    }
    return trimmed;
}

/**
 * @param {EnvReader} readEnv
 * @returns {string | undefined}
 */
export function getExplicitBuildVersion(readEnv) {
    const value = readEnv(EXPLICIT_BUILD_VERSION_ENV);
    return value === undefined ? undefined : normalizeExplicitBuildVersion(value);
}

/**
 * @param {EnvReader} readEnv
 * @returns {string | undefined}
 */
export function getGitHubTagName(readEnv) {
    const refName = readEnv("GITHUB_REF_NAME");
    if (readEnv("GITHUB_REF_TYPE") === "tag" && refName) return refName;

    const ref = readEnv("GITHUB_REF");
    if (ref?.startsWith("refs/tags/")) return ref.slice("refs/tags/".length) || undefined;

    return undefined;
}

/**
 * @param {GitRunner} runGit
 * @returns {string | undefined}
 */
export function getExactGitTag(runGit) {
    return runGit(["describe", "--tags", "--exact-match", "HEAD"]);
}

/**
 * @param {GitRunner} runGit
 * @returns {string | undefined}
 */
export function getGitShortHash(runGit) {
    const gitShortHash = runGit(["rev-parse", "--short", "HEAD"]);

    return gitShortHash || undefined;
}

/**
 * @param {BuildVersionPort} port
 * @returns {string}
 */
export function resolveBuildVersion(port) {
    const { readEnv, runGit } = port;

    return getExplicitBuildVersion(readEnv) ?? getGitHubTagName(readEnv) ?? getExactGitTag(runGit) ??
        getGitShortHash(runGit) ?? "dev";
}

/**
 * @param {string} filePath
 * @param {string} version
 * @returns {Promise<void>}
 */
export async function writeVersionFile(filePath, version) {
    const content = `/**
 * @module shared/version
 *
 * Generated by scripts/write-version.js. The build pipeline overwrites
 * this file with the current build version before \`deno compile\`.
 */

export const VERSION = ${JSON.stringify(version)};
`;

    let existingContent;
    try {
        existingContent = await Deno.readTextFile(filePath);
    } catch (error) {
        if (!(error instanceof Deno.errors.NotFound)) throw error;
    }

    if (existingContent === content) {
        console.log("[wld] version - ok");
        return;
    }

    await Deno.writeTextFile(filePath, content);
    console.log(`[wld] version - updated ${filePath} to version ${version}`);
}

if (import.meta.main) {
    await writeVersionFile(FILE_PATH, resolveBuildVersion({ readEnv: readEnvValue, runGit: runGitCommand }));
}
